### ISSUE TITLE
Mute/Unmute

### ISSUE THREAD

**Issue by vikrammittal** [opentok/accelerator-sample-apps-android#10]
Please let me know how to mute/unmute the stream I am watching. I am watching a stream which is been broadcasted by other user.  I want to view the stream but not listen the stream. So need a mute/unmute option.

**Comment by marinaserranomontes** [comment]
Hi @vikrammittal ,

Do you mean to mute the audio for a subscribed stream? 

Best,
Marina

**Comment by vikrammittal** [comment]
@marinaserranomontes yes.

**Comment by marinaserranomontes** [comment]
Hi @vikrammittal ,

Please note, in the OpenTok Android SDK we have a method to subscribe to the stream's audio (true) or not (false): "setSubscribeToAudio(boolean subscribeToAudio)".
Eg: mySubscriber.setSubscribeToAudio(false) --> mute the audio of the subscribed stream.

If you are using the accelerator-core-android lib, you can call to the method: "enableReceivedMedia(String remoteId, MediaType type, boolean enabled)". https://github.com/opentok/accelerator-core-android/blob/c88ff696dc1e39c28818e34ca4998378f0f4086b/accelerator-core/src/main/java/com/tokbox/android/otsdkwrapper/wrapper/OTWrapper.java#L409


Best,
Marina

**Comment by marinaserranomontes** [comment]
hi @vikrammittal ,

I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue. You can also contribute directly to samples by providing a patch.

Thank you!

Best,
Marina

**Comment by sakshivicesoftware** [comment]
how can we toggle between mute and unmute ?
