### ISSUE TITLE
Tokbox Android SDK 

### ISSUE THREAD

**Issue by venkypokala9009** [opentok/accelerator-sample-apps-android#14]
I have proper 4g network. but every time i am getting this error.

OTWrapper: Session: onError Unable to connect to the session: check the network connection.

**Comment by devwithzachary** [comment]
There has been a new release of the [Accelerator Core for Android](https://github.com/opentok/accelerator-core-android) and this sample app has been updated to use this. Please test with the latest versions and if you find any issue still remaining raise a new issue. Thank you!
