### ISSUE TITLE
Remote Stream Name

### ISSUE THREAD

**Issue by txusms** [opentok/accelerator-sample-apps-android#18]
I can setup a name in OTConfigBuilder when create a OTWrapper. But, how can I get the name of a remote subscriber?

Without accelerator-core, I can get subscriber name from Stream, but now I haven't access to Stream object.

Am I doing somethig wrong?

**Comment by devwithzachary** [comment]
There has been a new release of the [Accelerator Core for Android](https://github.com/opentok/accelerator-core-android) and this sample app has been updated to use this. Please test with the latest versions and if you find any issue still remaining raise a new issue. Thank you!
