### ISSUE TITLE
 com.opentok.android.v3.Session$SessionException: context or apiKey or session Id argument(s) is null

### ISSUE THREAD

**Issue by Vinodasv** [opentok/accelerator-sample-apps-android#22]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/opentok/accelerator-core-ios/blob/master/README.md) 
- [ ] I have searched [existing issues](https://github.com/opentok/accelerator-core-ios/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?
 com.opentok.android.v3.Session$SessionException: context or apiKey or session Id argument(s) is null
>...

## Question or Feature Request

> ...

**Comment by devwithzachary** [comment]
There has been a new release of the [Accelerator Core for Android](https://github.com/opentok/accelerator-core-android) and this sample app has been updated to use this. Please test with the latest versions and if you find any issue still remaining raise a new issue. Thank you!
