### ISSUE TITLE
Error: Not able to join Remote Session

### ISSUE THREAD

**Issue by srinivaskolla** [opentok/accelerator-sample-apps-android#24]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/opentok/accelerator-core-ios/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-ios/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):  com.opentok.android:opentok-accelerator-core:1.0.23
- iOS/Android/Browser version(s): Android
- Devices/Simulators/Machine affected: Samsung Tablet/LG Phone.
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

## Bug report

Just downloaded the app into android studio and changed API_KEY, SESSION, TOKEN.
Two problems.
1. If the session is already started in the web browser, android app is not connecting.
2. If web browser is started after the app starts the video chat, I am getting the following error.

_E/OTWrapper: Session: onError Unable to connect to a session that is already connected or unable to subscribe to a stream that is no longer in the session_

It won't show anything and app freezes. 

Couple of other issues noted

3. BasicListener --> public void onConnected() getting called twice.
4.  mWrapper.getRemoteStreamStatus(remoteId).getType() this is throwing NPE.

Please help

#### Expected behavior

> ...

#### Actual behavior

> E/OTWrapper: Session: onError Unable to connect to a session that is already connected or unable to subscribe to a stream that is no longer in the session.

#### Steps to reproduce

> Launch the app, Click on Phone Icon, Then Launch Webbrowser which has same sessionid.

#### Crash log? Screenshots? Videos? Sample project?

> 

## Question or Feature Request

> ...

**Comment by ankitgupta394** [comment]
Hi Team, 

I also facing connection issue in android. I am getting session publisher not found and camera failed error. But it was working fine before a week.

![opentok3](https://user-images.githubusercontent.com/17039214/94449662-f5deb680-01c9-11eb-9273-a46fa8d512eb.png)
![error for opentok2](https://user-images.githubusercontent.com/17039214/94449673-fa0ad400-01c9-11eb-8f61-76a308e65da3.png)

![error for opentok](https://user-images.githubusercontent.com/17039214/94449689-0000b500-01ca-11eb-90ba-cee4fd12da5b.png)


Please tell solution. 
we are facing this issue on production please tell something for fix

**Comment by devwithzachary** [comment]
There has been a new release of the [Accelerator Core for Android](https://github.com/opentok/accelerator-core-android) and this sample app has been updated to use this. Please test with the latest versions and if you find any issue still remaining raise a new issue. Thank you!
