### ISSUE TITLE
Multiple Remotes for ScreenSharing

### ISSUE THREAD

**Issue by warrenferns** [opentok/accelerator-sample-apps-android#28]
## New issue checklist

- [v] I have read all of the [`README`](https://github.com/opentok/accelerator-core-ios/blob/master/README.md) 
- [v] I have searched [existing issues](https://github.com/opentok/accelerator-core-ios/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior
The ScreenSharing featuring only shares the remote view of the app but I want the app to share the screens of the other apps too.. How is this possible?
> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by devwithzachary** [comment]
There has been a new release of the [Accelerator Core for Android](https://github.com/opentok/accelerator-core-android) and this sample app has been updated to use this. Please test with the latest versions and if you find any issue still remaining raise a new issue. Thank you!
